-- Corrected identity split, portal domain, publication model, finance invariants, and tested RLS foundation.
create schema if not exists private;
create schema if not exists api_internal;
create schema if not exists api_portal;

create type internal_role as enum ('founder_ceo','executive_operations','project_manager','department_lead','developer','designer','capture_specialist','videographer','photographer','editor','content_specialist','marketing_specialist','sales_specialist','contractor','freelancer','intern');
create type client_role as enum ('client_owner','client_project_approver','client_billing_contact','client_collaborator','client_viewer');
create type permission_action as enum ('client.read','client.update','client.internal_note.read','project.read','project.manage','project.publish','request.submit','request.triage','change_order.draft','change_order.internal_approve','change_order.client_approve','invoice.read','invoice.pay','payment.refund','document.upload','document.download','document.publish','finance.read','finance.post','finance.reconcile','access.grant','access.revoke','production.deploy');
create type publication_state as enum ('internal_draft','internal_review','approved_for_client','published_to_client','withdrawn','archived');
create type client_request_status as enum ('submitted','received','under_triage','needs_client_information','under_evaluation','estimate_in_preparation','awaiting_client_approval','approved','scheduled','in_progress','client_review','completed','rejected','canceled','converted_to_change_order');

alter table clients rename to client_organizations;
-- The rename carries the old `clients_member_read` policy over with it, still
-- gated on `internal_notes is null` — that column is dropped a few statements
-- below once client_internal_notes exists, which fails with a dependency error
-- unless the old policy is cleared first. Replace it with the is_internal_member()
-- gate this migration uses for every other table it introduces, so basic client
-- fields stay internally readable; fine-grained note access is governed by the
-- new client_internal_notes table's own policy below, not by hiding the whole row.
drop policy if exists clients_member_read on client_organizations;
create policy client_organizations_read on client_organizations for select
  using (organization_id in (select current_org_ids()));
alter table memberships rename to organization_memberships;
alter table organization_memberships add column if not exists internal_role internal_role;
update organization_memberships set internal_role = role::text::internal_role where role::text <> 'client' and internal_role is null;
alter table organization_memberships add constraint organization_memberships_no_client_role check (internal_role is not null and role::text <> 'client');

create table if not exists internal_permission_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), profile_id uuid not null references profiles(id), action permission_action not null, resource_type text, resource_id uuid, effective_from timestamptz not null default now(), effective_until timestamptz, granted_by uuid references profiles(id), revoked_at timestamptz, created_at timestamptz not null default now());
create table if not exists client_memberships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), profile_id uuid not null references profiles(id), role client_role not null, effective_from timestamptz not null default now(), effective_until timestamptz, suspended_at timestamptz, created_at timestamptz not null default now(), unique(client_organization_id, profile_id, role));
create table if not exists client_permission_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), profile_id uuid not null references profiles(id), action permission_action not null, project_id uuid references projects(id), document_classification data_classification, effective_from timestamptz not null default now(), effective_until timestamptz, granted_by uuid references profiles(id), revoked_at timestamptz, created_at timestamptz not null default now());
create table if not exists project_access_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), project_id uuid not null references projects(id), client_organization_id uuid references client_organizations(id), profile_id uuid references profiles(id), action permission_action not null default 'project.read', effective_from timestamptz not null default now(), effective_until timestamptz, revoked_at timestamptz, created_by uuid references profiles(id), created_at timestamptz not null default now());
create table if not exists temporary_access_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), profile_id uuid not null references profiles(id), action permission_action not null, resource_type text not null, resource_id uuid not null, effective_from timestamptz not null default now(), effective_until timestamptz not null, revoked_at timestamptz, created_by uuid references profiles(id), created_at timestamptz not null default now(), check (effective_until > effective_from));
create table if not exists delegations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), delegator_id uuid not null references profiles(id), delegate_id uuid not null references profiles(id), action permission_action not null, effective_from timestamptz not null default now(), effective_until timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now(), check (delegator_id <> delegate_id));
create table if not exists access_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), subject_profile_id uuid not null references profiles(id), reviewer_id uuid references profiles(id), status record_status not null default 'draft', due_at timestamptz not null, completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists portal_invitations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), email text not null, initial_role client_role not null, invited_by uuid not null references profiles(id), token_hash text not null unique, expires_at timestamptz not null, revoked_at timestamptz, accepted_by uuid references profiles(id), accepted_at timestamptz, created_at timestamptz not null default now(), check (expires_at > created_at));

create table if not exists client_internal_notes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), body text not null, created_by uuid references profiles(id), created_at timestamptz not null default now());
alter table client_organizations drop column if exists internal_notes;

create table if not exists client_publications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), project_id uuid references projects(id), source_table text not null, source_id uuid not null, title text not null, summary text not null, state publication_state not null default 'internal_draft', published_at timestamptz, published_by uuid references profiles(id), version_hash text, created_at timestamptz not null default now());
create table if not exists client_updates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), publication_id uuid not null references client_publications(id), body text not null, created_at timestamptz not null default now());
create table if not exists client_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), project_id uuid references projects(id), submitted_by uuid not null references profiles(id), title text not null, body text not null, status client_request_status not null default 'submitted', evidence jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists request_status_history (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_request_id uuid not null references client_requests(id), from_status client_request_status, to_status client_request_status not null, changed_by uuid references profiles(id), client_visible boolean not null default false, created_at timestamptz not null default now());
create table if not exists request_comments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_request_id uuid not null references client_requests(id), author_id uuid not null references profiles(id), body text not null, visibility text not null check (visibility in ('internal','client')), created_at timestamptz not null default now());
create table if not exists request_attachments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_request_id uuid not null references client_requests(id), document_id uuid references documents(id), created_at timestamptz not null default now());
create table if not exists request_triage (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_request_id uuid not null references client_requests(id), internal_owner_id uuid references profiles(id), internal_priority text, internal_cost_estimate_minor bigint, internal_classification data_classification not null default 'internal', created_at timestamptz not null default now());

create table if not exists change_orders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), client_organization_id uuid not null references client_organizations(id), project_id uuid not null references projects(id), client_request_id uuid references client_requests(id), status record_status not null default 'draft', created_by uuid references profiles(id), created_at timestamptz not null default now());
create table if not exists change_order_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), change_order_id uuid not null references change_orders(id), version_number int not null, state publication_state not null default 'internal_draft', scope_summary text not null, price_minor bigint not null check (price_minor >= 0), currency char(3) not null, version_hash text not null, accepted_at timestamptz, created_at timestamptz not null default now(), unique(change_order_id, version_number));
create table if not exists change_order_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), change_order_version_id uuid not null references change_order_versions(id), description text not null, amount_minor bigint not null check (amount_minor >= 0), currency char(3) not null);
create table if not exists change_order_internal_approvals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), change_order_version_id uuid not null references change_order_versions(id), approver_id uuid not null references profiles(id), decision text not null check (decision in ('approved','rejected')), created_at timestamptz not null default now(), unique(change_order_version_id, approver_id));
create table if not exists change_order_client_decisions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), change_order_version_id uuid not null references change_order_versions(id), client_organization_id uuid not null references client_organizations(id), decided_by uuid not null references profiles(id), decision text not null check (decision in ('accepted','rejected')), evidence jsonb not null default '{}', created_at timestamptz not null default now(), unique(change_order_version_id, client_organization_id));

create table if not exists accounting_periods (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), period_start date not null, period_end date not null, locked_at timestamptz, locked_by uuid references profiles(id), unique(organization_id, period_start), check (period_end >= period_start));
create table if not exists posting_idempotency_keys (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), idempotency_key text not null, journal_entry_id uuid references journal_entries(id), created_at timestamptz not null default now(), unique(organization_id, idempotency_key));
alter table journal_lines drop constraint if exists journal_lines_check;
alter table journal_lines add constraint journal_lines_exactly_one_positive_side check ((debit_minor > 0 and credit_minor = 0) or (credit_minor > 0 and debit_minor = 0));
create or replace function prevent_posted_journal_line_update() returns trigger language plpgsql as $$ begin if exists (select 1 from journal_entries je where je.id = old.journal_entry_id and je.status = 'posted') then raise exception 'posted_journal_lines_are_immutable'; end if; return new; end $$;
drop trigger if exists journal_lines_immutable on journal_lines;
create trigger journal_lines_immutable before update or delete on journal_lines for each row execute function prevent_posted_journal_line_update();
create or replace function post_journal_entry(p_entry_id uuid, p_actor_id uuid, p_idempotency_key text) returns uuid language plpgsql security definer as $$ declare v_org uuid; v_status record_status; v_debit bigint; v_credit bigint; v_lines int; v_currency_count int; begin select organization_id, status into v_org, v_status from journal_entries where id = p_entry_id for update; if v_org is null then raise exception 'journal_entry_not_found'; end if; if v_status <> 'draft' then raise exception 'only_draft_entries_can_be_posted'; end if; if exists (select 1 from accounting_periods ap where ap.organization_id = v_org and ap.locked_at is not null and current_date between ap.period_start and ap.period_end) then raise exception 'accounting_period_locked'; end if; insert into posting_idempotency_keys (organization_id, idempotency_key, journal_entry_id) values (v_org, p_idempotency_key, p_entry_id); select count(*), coalesce(sum(debit_minor),0), coalesce(sum(credit_minor),0), count(distinct currency) into v_lines, v_debit, v_credit, v_currency_count from journal_lines where journal_entry_id = p_entry_id; if v_lines < 2 then raise exception 'journal_requires_at_least_two_lines'; end if; if v_currency_count <> 1 then raise exception 'mixed_currency_journal_requires_documented_fx_flow'; end if; if v_debit <> v_credit then raise exception 'journal_entry_must_balance'; end if; update journal_entries set status = 'posted', posted_at = now() where id = p_entry_id; insert into audit_events (organization_id, actor_id, action, target_table, target_id, classification, metadata) values (v_org, p_actor_id, 'finance.post', 'journal_entries', p_entry_id, 'restricted', jsonb_build_object('idempotency_key', p_idempotency_key)); return p_entry_id; end $$;

create or replace function is_internal_member(org uuid) returns boolean language sql stable as $$ select exists(select 1 from organization_memberships where profile_id=auth.uid() and organization_id=org and suspended_at is null and internal_role is not null and (effective_until is null or effective_until > now())) $$;
create or replace function is_portal_member(client_org uuid) returns boolean language sql stable as $$ select exists(select 1 from client_memberships where profile_id=auth.uid() and client_organization_id=client_org and suspended_at is null and (effective_until is null or effective_until > now())) $$;
create or replace function has_project_access(pid uuid) returns boolean language sql stable as $$ select exists(select 1 from project_memberships where profile_id=auth.uid() and project_id=pid and (effective_until is null or effective_until > now())) or exists(select 1 from project_access_grants where profile_id=auth.uid() and project_id=pid and revoked_at is null and (effective_until is null or effective_until > now())) $$;
create or replace view api_portal.published_project_updates as select cp.id, cp.organization_id, cp.client_organization_id, cp.project_id, cp.title, cp.summary, cp.published_at from client_publications cp where cp.state = 'published_to_client';

alter table internal_permission_grants enable row level security; alter table client_memberships enable row level security; alter table client_permission_grants enable row level security; alter table project_access_grants enable row level security; alter table temporary_access_grants enable row level security; alter table delegations enable row level security; alter table access_reviews enable row level security; alter table portal_invitations enable row level security; alter table client_internal_notes enable row level security; alter table client_publications enable row level security; alter table client_updates enable row level security; alter table client_requests enable row level security; alter table request_status_history enable row level security; alter table request_comments enable row level security; alter table request_attachments enable row level security; alter table request_triage enable row level security; alter table change_orders enable row level security; alter table change_order_versions enable row level security; alter table change_order_items enable row level security; alter table change_order_internal_approvals enable row level security; alter table change_order_client_decisions enable row level security; alter table accounting_periods enable row level security; alter table posting_idempotency_keys enable row level security;
create policy internal_grants_exec on internal_permission_grants for all using (is_executive(organization_id)) with check (is_executive(organization_id));
create policy client_membership_self_or_internal on client_memberships for select using (is_internal_member(organization_id) or profile_id = auth.uid());
create policy project_access_internal on project_access_grants for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy portal_invitations_internal on portal_invitations for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy client_internal_notes_internal on client_internal_notes for select using (is_internal_member(organization_id));
create policy client_publications_internal_all on client_publications for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy client_publications_portal_read on client_publications for select using (state='published_to_client' and is_portal_member(client_organization_id));
create policy client_requests_portal_insert on client_requests for insert with check (submitted_by=auth.uid() and is_portal_member(client_organization_id) and status='submitted');
create policy client_requests_portal_read on client_requests for select using (is_portal_member(client_organization_id));
create policy client_requests_internal on client_requests for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy request_history_scoped on request_status_history for select using (is_internal_member(organization_id) or (client_visible and exists(select 1 from client_requests cr where cr.id=client_request_id and is_portal_member(cr.client_organization_id))));
create policy request_comments_scoped on request_comments for select using (is_internal_member(organization_id) or (visibility='client' and exists(select 1 from client_requests cr where cr.id=client_request_id and is_portal_member(cr.client_organization_id))));
create policy request_triage_internal on request_triage for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy change_orders_internal on change_orders for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy change_versions_internal on change_order_versions for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy change_versions_portal_read on change_order_versions for select using (state='published_to_client' and exists(select 1 from change_orders co where co.id=change_order_id and is_portal_member(co.client_organization_id)));
create policy change_client_decisions_insert on change_order_client_decisions for insert with check (decided_by=auth.uid() and is_portal_member(client_organization_id));
create policy finance_periods_exec on accounting_periods for all using (is_executive(organization_id)) with check (is_executive(organization_id));
create policy posting_keys_exec on posting_idempotency_keys for select using (is_executive(organization_id));


create policy client_permission_grants_internal on client_permission_grants for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy temporary_access_internal on temporary_access_grants for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy delegations_internal on delegations for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy access_reviews_internal on access_reviews for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy client_updates_internal on client_updates for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy client_updates_portal_read on client_updates for select using (exists(select 1 from client_publications cp where cp.id = publication_id and cp.state = 'published_to_client' and is_portal_member(cp.client_organization_id)));
create policy request_attachments_internal on request_attachments for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy request_attachments_portal_read on request_attachments for select using (exists(select 1 from client_requests cr where cr.id = client_request_id and is_portal_member(cr.client_organization_id)));
create policy change_order_items_internal on change_order_items for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy change_order_items_portal_read on change_order_items for select using (exists(select 1 from change_order_versions cov join change_orders co on co.id = cov.change_order_id where cov.id = change_order_version_id and cov.state = 'published_to_client' and is_portal_member(co.client_organization_id)));
create policy change_internal_approvals_internal on change_order_internal_approvals for all using (is_internal_member(organization_id)) with check (is_internal_member(organization_id));
create policy change_client_decisions_read on change_order_client_decisions for select using (is_internal_member(organization_id) or is_portal_member(client_organization_id));
